# Generated by Django 4.2.7 on 2023-11-16 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0002_conversation_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="admin_id",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="customer_id",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="vendor_id",
        ),
        migrations.AddField(
            model_name="conversation",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
